#!/usr/bin/env bash
# print domains and subdomains

function check_dns_record {
    local domain=$1
    local subdomain=$2
    local record_type=$3

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(nslookup -type="$record_type" "$sub.$domain" | awk '/^'"$sub"'/ {print $NF}')
        echo "The subdomain $sub is a $record_type record and points to $result"
    done
}

domain=$1
subdomain=$2
check_dns_record "$domain" "$subdomain" "A"
