#!/usr/bin/env bash
# Install Nginx where it should be listening on port 80
# Querying Nginx at its root / with a GET request using curl,
# must return a page that contains the string 'Hello World!'

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create index.html file with Hello World!
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Check that Nginx is serving the "Hello World!" message
curl http://localhost
