#!/usr/bin/env bash
# Install Nginx where it should be listening on port 80

# Updating package list and installing Nginx
echo -e "Updating package list and installing Nginx.\n"
sudo apt -y update && sudo apt -y install nginx

# Performing some setting
echo -e "\nPerforming some setting.\n"

# Starting Nginx
sudo service nginx start

# Adjusting the Firewall
sudo ufw allow 'Nginx HTTP'

# Assigning ownership with the $USER environment variable
sudo chown -R "$USER":"$USER" /var/www/html

# Setting up default file permissions
sudo chmod -R 755 /var/www

# Creating index.html file containing the string 'Hello World!'
echo "Hello World!" > /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.htm
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configuring Nginx to listen on port 80 and serve the index.html file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
}" > /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart
