#!/usr/bin/env bash
# Script to install nginx & configure it to listen on port 80
# Using curl must return a page contains the string "Hello World"

# Update
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Starting nginx
sudo service nginx start

# Allowing nginx on Firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart
