#!/usr/bin/env bash
# Configure Nginx so that /redirect_me is redirecting to another page

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Assign ownership of /var/www with the $USER environment variable
sudo chown -R "$USER":"$USER" /var/www

# Create new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Set /redirect_me to a youtube video
sudo sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
