#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Assign ownership of /var/www with the $USER environment variable
sudo chown -R "$USER":"$USER" /var/www

# Create new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use custom 404 page
sudo sed -i "s/#error_page 404/error_page 404/g" /etc/nginx/sites-available/default
sudo sed -i "s|#error_page 404.*|error_page 404 /404.html;|g" /etc/nginx/sites-available/default
sudo sed -i "s|#location = /404.html {|location = /404.html {|g" /etc/nginx/sites-available/default
sudo sed -i "s|#}|}|g" /etc/nginx/sites-available/default
sudo sed -i "s|#}|}|g" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
