#!/usr/bin/env bash
# Configure Nginx to have a custion 404 page that contains
# the string "Ceci n'est pas une page"

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Adjust Firewall to allow access to Nginx
sudo ufw allow 'Nginx HTTP'

# Create a 404.html file containing the given string
echo "Ceci n'est pas une page" > /var/www/nginx/html/error_404.html
sudo sed -i "25i\       error_page 404 /error_404.html;" /etc/nginx/sites-available/default

# Start Nginx
sudo service nginx start
