#!/usr/bin/env bash
# This script creates a file named the same as an argument entered in the
# prompt shell

read -rp "Enter a filename: " filename
touch "$filename"
chmod u+x "$filename"
echo "#!/usr/bin/env bash" > "$filename"
echo "# This script" >> "$filename"

echo "File $filename created!"
