#!/usr/bin/env bash
# This script configures an Ubuntu server with requirements
cp /etc/hosts ~/hosts.new
sed -i s/^172.*$// ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
