#!/usr/bin/env bash
# This script configures an Ubuntu server with requirements
cp /etc/hosts ~/hosts.new
sed -e 's/127.0.0.1/127.0.0.2' ~/hosts.new
sed -e '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
