#!/usr/bin/env bash
# This script configures an Ubuntu server with requirements
if [ ! -f /etc/hosts ]
then
    touch /etc/hosts
fi

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

systemctl restart networking
